name: Deploy React App to Azure

on: workflow_dispatch

env:
  RESOURCE_GROUP_EU: rg-eshoponweb-westeurope
  RESOURCE_GROUP_US: rg-eshoponweb-eastus
  WEBAPP_NAME_EU: ${{ secrets.WEBAPP_NAME_EU }}
  WEBAPP_NAME_US: ${{ secrets.WEBAPP_NAME_US }}
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  APP_SERVICE_PLAN_EU: myAppServicePlanEU
  APP_SERVICE_PLAN_US: myAppServicePlanUS

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Build Project
        run: npm run build
        
      - name: Zip the build directory
        run: zip -r build.zip ./build

      - name: Login to Azure
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create or Update EU App Service Plan
        run: |
          az appservice plan show --name ${{ env.APP_SERVICE_PLAN_EU }} --resource-group ${{ env.RESOURCE_GROUP_EU }} --subscription ${{ secrets.SUBSCRIPTION_ID }} || \
          az appservice plan create --name ${{ env.APP_SERVICE_PLAN_EU }} --resource-group ${{ env.RESOURCE_GROUP_EU }} --sku B1 --is-linux --subscription ${{ secrets.SUBSCRIPTION_ID }}

      - name: Create or Update US App Service Plan
        run: |
          az appservice plan show --name ${{ env.APP_SERVICE_PLAN_US }} --resource-group ${{ env.RESOURCE_GROUP_US }} --subscription ${{ secrets.SUBSCRIPTION_ID }} || \
          az appservice plan create --name ${{ env.APP_SERVICE_PLAN_US }} --resource-group ${{ env.RESOURCE_GROUP_US }} --sku B1 --is-linux --subscription ${{ secrets.SUBSCRIPTION_ID }}

      - name: Create or Update EU Web App
        run: |
          az webapp show --name ${{ env.WEBAPP_NAME_EU }} --resource-group ${{ env.RESOURCE_GROUP_EU }} --subscription ${{ secrets.SUBSCRIPTION_ID }} || \
          az webapp create --name ${{ env.WEBAPP_NAME_EU }} --resource-group ${{ env.RESOURCE_GROUP_EU }} --plan ${{ env.APP_SERVICE_PLAN_EU }} --runtime "NODE|18-lts" --subscription ${{ secrets.SUBSCRIPTION_ID }}

      - name: Create or Update US Web App
        run: |
          az webapp show --name ${{ env.WEBAPP_NAME_US }} --resource-group ${{ env.RESOURCE_GROUP_US }} --subscription ${{ secrets.SUBSCRIPTION_ID }} || \
          az webapp create --name ${{ env.WEBAPP_NAME_US }} --resource-group ${{ env.RESOURCE_GROUP_US }} --plan ${{ env.APP_SERVICE_PLAN_US }} --runtime "NODE|18-lts" --subscription ${{ secrets.SUBSCRIPTION_ID }}

      - name: Deploy to Azure EU Web App
        run: |
          az webapp deploy --resource-group ${{ env.RESOURCE_GROUP_EU }} \
            --name ${{ env.WEBAPP_NAME_EU }} --src-path build.zip \
            --subscription ${{ secrets.SUBSCRIPTION_ID }} --type zip

      - name: Deploy to Azure US Web App
        run: |
          az webapp deploy --resource-group ${{ env.RESOURCE_GROUP_US }} \
            --name ${{ env.WEBAPP_NAME_US }} --src-path build.zip \
            --subscription ${{ secrets.SUBSCRIPTION_ID }} --type zip
