name: Deploy React App to Vercel and Azure

on: workflow_dispatch

env:
  RESOURCE_GROUP_EU: rg-eshoponweb-westeurope
  RESOURCE_GROUP_US: rg-eshoponweb-eastus
  WEBAPP_NAME_EU: ${{ secrets.WEBAPP_NAME_EU }}
  WEBAPP_NAME_US: ${{ secrets.WEBAPP_NAME_US }}
  SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
        
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        
      - name: Build Project Artifacts
        run: npm run build
        
      - name: Zip build directory
        run: zip -r build.zip build
        
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Login to Azure
        uses: Azure/login@v2.2.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure EU Web App
        run: |
          az webapp deployment source config-zip --resource-group ${{ env.RESOURCE_GROUP_EU }} \
            --name ${{ env.WEBAPP_NAME_EU }} --src-path ./build.zip \
            --subscription ${{ secrets.SUBSCRIPTION_ID }}

      - name: Deploy to Azure US Web App
        run: |
          az webapp deployment source config-zip --resource-group ${{ env.RESOURCE_GROUP_US }} \
            --name ${{ env.WEBAPP_NAME_US }} --src-path ./build.zip \
            --subscription ${{ secrets.SUBSCRIPTION_ID }}
